version: '3'

services:
  php_apache:
    build: 
      args:
        user: ${DOCKER_USER:-docker}
        uid: ${DOCKER_UID:-1000}
      context: ./
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
